// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfHn6waQ-IFlQCtyRVH4oYFmM3txAZ29I',
    appId: '1:344409261247:web:c055fd2241015462b3320a',
    messagingSenderId: '344409261247',
    projectId: 'sinflixapp-3fb29',
    authDomain: 'sinflixapp-3fb29.firebaseapp.com',
    storageBucket: 'sinflixapp-3fb29.firebasestorage.app',
    measurementId: 'G-KWRRS1417P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk8vlBf6MgUx-s-ERV4xVnDddnzP_2ohs',
    appId: '1:344409261247:android:e91efaff6ebda537b3320a',
    messagingSenderId: '344409261247',
    projectId: 'sinflixapp-3fb29',
    storageBucket: 'sinflixapp-3fb29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsE4LMnS0u5-keJDawhCH3nI6Lu4qVr8',
    appId: '1:344409261247:ios:815063632f26ed52b3320a',
    messagingSenderId: '344409261247',
    projectId: 'sinflixapp-3fb29',
    storageBucket: 'sinflixapp-3fb29.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDsE4LMnS0u5-keJDawhCH3nI6Lu4qVr8',
    appId: '1:344409261247:ios:815063632f26ed52b3320a',
    messagingSenderId: '344409261247',
    projectId: 'sinflixapp-3fb29',
    storageBucket: 'sinflixapp-3fb29.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfHn6waQ-IFlQCtyRVH4oYFmM3txAZ29I',
    appId: '1:344409261247:web:fececd521261a5c7b3320a',
    messagingSenderId: '344409261247',
    projectId: 'sinflixapp-3fb29',
    authDomain: 'sinflixapp-3fb29.firebaseapp.com',
    storageBucket: 'sinflixapp-3fb29.firebasestorage.app',
    measurementId: 'G-QXZSQVZ4ZV',
  );
}
